export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const INPUT_AMOUNT = "INPUT_AMOUNT";
export const INPUT_AMOUNT_FAILED = "INPUT_AMOUNT_FAILED";

export const BILL_ACCOUNT_TYPE = "BILL_ACCOUNT_TYPE";
export const BILL_ACCOUNT_TYPE_FAILED = "BILL_ACCOUNT_TYPE_FAILED";

export const BILL_ACCOUNT_INFO = "BILL_ACCOUNT_INFO";
export const BILL_ACCOUNT_INFO_FAILED = "BILL_ACCOUNT_INFO_FAILED";